services:
  app:
    image: taphadiopdev/isi_burger:latest
    container_name: examenlaravel3-app-1
    command: sh -c "rm -f public/storage && php artisan storage:link && apache2-foreground"
    ports:
      - "8086:80"
    volumes:
      - C:/laragon/www/examenlaravel3/storage/app/public:/var/www/html/storage/app/public
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_DATABASE=ExamenLaravel2
      - DB_USERNAME=postgres
      - DB_PASSWORD=passer
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=moistaphadiop57@gmail.com
      - MAIL_PASSWORD=yqowzfqipdcoyzlw
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=moistaphadiop57@gmail.com
      - MAIL_FROM_NAME="ISI BURGER"
    networks:
      - burger-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: examenlaravel3-mailpit-1
    ports:
      - "8025:8025"
    networks:
      - burger-network

networks:
  burger-network:
    driver: bridge