services:
  app:
    image: taphadiopdev/isi_burger:latest  # Utilise l'image buildée par Jenkins
    container_name: examenlaravel3-app-1
    ports:
      - "8086:80"
    volumes:
      - .:/var/www/html
      # On retire le lien absolu vers C:/laragon pour éviter les erreurs de permission
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_DATABASE=ExamenLaravel2
      - DB_USERNAME=postgres
      - DB_PASSWORD=passer
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
    networks:
      - burger-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: examenlaravel3-mailpit-1
    ports:
      - "8025:8025"
    networks:
      - burger-network

networks:
  burger-network:
    driver: bridge